### ISSUE TITLE
roboter broken after webpack upgrade

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#52]
After upgrading to webpack 4.0.1, roboter is completely broken.

every call to `bot` fails with:
```
/home/stheine/js/quixy/node_modules/webpack/lib/webpack.js:159
                        throw new RemovedPluginError(errorMessage);
                        ^

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
    at Object.get [as UglifyJsPlugin] (/home/stheine/js/quixy/node_modules/webpack/lib/webpack.js:159:10)
    at getWebpackConfiguration (/home/stheine/js/quixy/node_modules/roboter/lib/tasks/client/build-app/index.js:82:28)
    at buildApp (/home/stheine/js/quixy/node_modules/roboter/lib/tasks/client/build-app/index.js:90:32)
    at Object.keys.filter.forEach.taskName (/home/stheine/js/quixy/node_modules/roboter/lib/roboter.js:75:7)
    at Array.forEach (<anonymous>)
    at Roboter.start (/home/stheine/js/quixy/node_modules/roboter/lib/roboter.js:68:5)
    at Object.<anonymous> (/home/stheine/js/quixy/roboter.js:173:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

this is caused by the line:
https://github.com/thenativeweb/roboter/blob/master/lib/tasks/client/build-app/index.js#L82

is there a simple way to prevent that from being called by some config in roboter.js? we don't use the `build-app` task at all, but we would like to use other tasks of roboter.

**Comment by goloroden** [comment]
Hi @stefanheine 😊 

We won't fix this for the current roboter, but we should have a plan for this for the next one.

So maybe we should discuss this as part of #50
