### ISSUE TITLE
Reflect is not defined

### ISSUE THREAD

**Issue by leschekfm** [thenativeweb/roboter#9]
I just wanted to try the module. After installing roboter in a project, installing the cli module globally and creating a roboter.js file in the project, running `bot` results in the following exception:
```
./node_modules/roboter/lib/tasks/universal/coverage/index.js:32
  Reflect.deleteProperty(configuration, 'threshold');
  ^

ReferenceError: Reflect is not defined
    at userConfiguration (./node_modules/roboter/lib/tasks/universal/coverage/index.js:32:3)
    at ./node_modules/roboter/lib/roboter.js:57:5
    at Array.forEach (native)
    at Roboter.useFolder.Roboter.start.Object.keys.forEach [as start] (./node_modules/roboter/lib/roboter.js:50:27)
    at Object.<anonymous> (./roboter.js:7:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

I can't find any other occurrence of 'reflect' anywhere else in the project.

**Comment by leschekfm** [comment]
Just checked current version 0.10.1 is broken, last working version is 0.8.2

**Comment by goloroden** [comment]
Thanks for bringing up this issue :-)

Unfortunately, roboter meanwhile only supports Node.js >= 6 and npm >= 3.
That's why it does not work :-(
